### PR TITLE
Fix deprecation warning for AtomicUsize

### PR DESCRIPTION
**Pull request by raskchanky**
Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by fnichol** [comment]
Nice, thanks!

tenor-220775320

This reminds me of a couple of other 2018 updates I had in a branch which I hadn't pushed. If I don't get to those by Sunday evening, I'll release an 0.10.0 so you're good again. 🎉

**Comment by raskchanky** [comment]
Thanks Fletcher!

**Comment by fnichol** [comment]
A few hours late, but features [0.10.0](https://crates.io/crates/features/0.10.0) is released for upgrading.

I have a few other updates which shouldn't affect any current behavior, but will drop the extra explicit dependency consumers have on bitflags and will provide a slightly better calling syntax (i.e. my first pass at Rust macros was very so-so).

tenor-131502301

**Pull request merged**
